name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: 'cd /home/vimracing && git pull && yarn && cd backend && yarn run build && pm2 delete -s vimracing || : && pm2 start dist/index.js --name vimracing'
